import type { GameLevel } from "./types";

export const levels: GameLevel[] = [
  {
    id: 1,
    title: "Падающий стакан",
    description: "Стакан соскользнул со стола.",
    timeLimitMs: 1800,
    successText: "Поймал! Минус одна уборка.",
    failText: "Хрусь. Теперь нужен веник.",
    target: {
      x: 54,
      y: 63,
      width: 30,
      height: 18,
      label: "Рука",
    },
    scene: {
      type: "falling-glass",
      emoji: "🥛",
      dangerEmoji: "💥",
      helperEmoji: "✋",
    },
  },
  {
    id: 2,
    title: "Кот и вода",
    description: "Кот летит туда, куда коты не хотят.",
    timeLimitMs: 1700,
    successText: "Кот спасён. Но всё ещё недоволен.",
    failText: "Кот мокрый. Ты в чёрном списке.",
    target: {
      x: 34,
      y: 70,
      width: 34,
      height: 17,
      label: "Подушка",
    },
    scene: {
      type: "cat-water",
      emoji: "🐱",
      dangerEmoji: "💧",
      helperEmoji: "🛏️",
    },
  },
  {
    id: 3,
    title: "Машина и яма",
    description: "Колёса уже почти увидели бездну.",
    timeLimitMs: 1900,
    successText: "Мост появился вовремя!",
    failText: "Машина теперь подземная.",
    target: {
      x: 51,
      y: 58,
      width: 35,
      height: 17,
      label: "Мост",
    },
    scene: {
      type: "car-pit",
      emoji: "🚗",
      dangerEmoji: "🕳️",
      helperEmoji: "🪵",
    },
  },
  {
    id: 4,
    title: "Ракета и планета",
    description: "Курс проложен слишком уверенно.",
    timeLimitMs: 1600,
    successText: "Космос спасён. Пока что.",
    failText: "Бум. Очень научно.",
    target: {
      x: 14,
      y: 70,
      width: 28,
      height: 18,
      label: "Поворот",
    },
    scene: {
      type: "rocket-planet",
      emoji: "🚀",
      dangerEmoji: "🪐",
      helperEmoji: "↩️",
    },
  },
  {
    id: 5,
    title: "Повар и торт",
    description: "Торт выбрал путь вниз.",
    timeLimitMs: 1800,
    successText: "Торт спасён. Можно праздновать.",
    failText: "Торт стал ковром.",
    target: {
      x: 36,
      y: 69,
      width: 33,
      height: 16,
      label: "Тарелка",
    },
    scene: {
      type: "chef-cake",
      emoji: "🎂",
      dangerEmoji: "🧹",
      helperEmoji: "🍽️",
    },
  },
  {
    id: 6,
    title: "Телефон падает",
    description: "Экран уже пишет завещание.",
    timeLimitMs: 1500,
    successText: "Экран жив. Кошелёк тоже.",
    failText: "Трещина в форме молнии.",
    target: {
      x: 45,
      y: 72,
      width: 28,
      height: 16,
      label: "Чехол",
    },
    scene: {
      type: "phone-fall",
      emoji: "📱",
      dangerEmoji: "⚡",
      helperEmoji: "🧸",
    },
  },
  {
    id: 7,
    title: "Мяч летит в окно",
    description: "Стекло пока верит в лучшее.",
    timeLimitMs: 1650,
    successText: "Поймал! Соседи не узнают.",
    failText: "Дзынь. Очень дорогой звук.",
    target: {
      x: 52,
      y: 46,
      width: 30,
      height: 19,
      label: "Перчатка",
    },
    scene: {
      type: "ball-window",
      emoji: "⚽",
      dangerEmoji: "🪟",
      helperEmoji: "🧤",
    },
  },
  {
    id: 8,
    title: "Пицца горит",
    description: "Сыр перешёл в режим тревоги.",
    timeLimitMs: 1400,
    successText: "Пицца спасена на грани.",
    failText: "Ужин стал углём.",
    target: {
      x: 65,
      y: 38,
      width: 22,
      height: 18,
      label: "Выключить",
    },
    scene: {
      type: "pizza-fire",
      emoji: "🍕",
      dangerEmoji: "🔥",
      helperEmoji: "🔴",
    },
  },
  {
    id: 9,
    title: "Птичка и кактус",
    description: "Маршрут построен слишком колюче.",
    timeLimitMs: 1750,
    successText: "Птичка ушла на мягкий маршрут.",
    failText: "Птичка стала колючей.",
    target: {
      x: 35,
      y: 27,
      width: 34,
      height: 18,
      label: "Облако",
    },
    scene: {
      type: "bird-cactus",
      emoji: "🐦",
      dangerEmoji: "🌵",
      helperEmoji: "☁️",
    },
  },
  {
    id: 10,
    title: "Робот и банановая кожура",
    description: "Алгоритм не видит жёлтую угрозу.",
    timeLimitMs: 1500,
    successText: "Робот продолжил миссию.",
    failText: "Ошибка 404: равновесие не найдено.",
    target: {
      x: 58,
      y: 70,
      width: 27,
      height: 16,
      label: "Кожура",
    },
    scene: {
      type: "robot-banana",
      emoji: "🤖",
      dangerEmoji: "🍌",
      helperEmoji: "🍌",
    },
  },
  {
    id: 11,
    title: "Зонт и дождь",
    description: "Облако уже собирает капли.",
    timeLimitMs: 1600,
    successText: "Сухо и красиво.",
    failText: "Мокрый стиль тоже стиль.",
    target: {
      x: 35,
      y: 56,
      width: 30,
      height: 18,
      label: "Зонт",
    },
    scene: {
      type: "rain-umbrella",
      emoji: "🧍",
      dangerEmoji: "🌧️",
      helperEmoji: "☂️",
    },
  },
  {
    id: 12,
    title: "Лампочка падает",
    description: "Лампочка решила уйти с потолка.",
    timeLimitMs: 1450,
    successText: "Свет спасён.",
    failText: "Темнота победила.",
    target: {
      x: 34,
      y: 73,
      width: 34,
      height: 15,
      label: "Коробка",
    },
    scene: {
      type: "falling-bulb",
      emoji: "💡",
      dangerEmoji: "🌑",
      helperEmoji: "📦",
    },
  },
  {
    id: 13,
    title: "Рыба без воды",
    description: "Рыба выпрыгнула из аквариума.",
    timeLimitMs: 1700,
    successText: "Рыба снова дома.",
    failText: "Рыба задумалась о жизни.",
    target: {
      x: 30,
      y: 59,
      width: 40,
      height: 23,
      label: "Аквариум",
    },
    scene: {
      type: "fish-tank",
      emoji: "🐟",
      dangerEmoji: "💨",
      helperEmoji: "🫧",
    },
  },
  {
    id: 14,
    title: "Будильник орёт",
    description: "Сон держится из последних сил.",
    timeLimitMs: 1400,
    successText: "Тишина восстановлена.",
    failText: "Соседи тоже проснулись.",
    target: {
      x: 41,
      y: 43,
      width: 27,
      height: 18,
      label: "Выкл",
    },
    scene: {
      type: "alarm-clock",
      emoji: "⏰",
      dangerEmoji: "🔊",
      helperEmoji: "🔕",
    },
  },
  {
    id: 15,
    title: "Книга падает на голову",
    description: "Полка решила поделиться знаниями.",
    timeLimitMs: 1650,
    successText: "Голова защищена.",
    failText: "Знания ударили сверху.",
    target: {
      x: 36,
      y: 63,
      width: 32,
      height: 17,
      label: "Шлем",
    },
    scene: {
      type: "falling-book",
      emoji: "📚",
      dangerEmoji: "😵",
      helperEmoji: "⛑️",
    },
  },
  {
    id: 16,
    title: "Мороженое тает",
    description: "Солнце смотрит слишком пристально.",
    timeLimitMs: 1500,
    successText: "Мороженое выжило.",
    failText: "Осталась сладкая лужа.",
    target: {
      x: 55,
      y: 55,
      width: 32,
      height: 24,
      label: "Холодильник",
    },
    scene: {
      type: "melting-icecream",
      emoji: "🍦",
      dangerEmoji: "☀️",
      helperEmoji: "🧊",
    },
  },
  {
    id: 17,
    title: "Поезд уезжает",
    description: "Платформа уже машет рукой.",
    timeLimitMs: 1550,
    successText: "Успел в последнюю секунду.",
    failText: "Следующий через 3 часа.",
    target: {
      x: 23,
      y: 61,
      width: 30,
      height: 18,
      label: "Ускоритель",
    },
    scene: {
      type: "train-rush",
      emoji: "🏃",
      dangerEmoji: "🚆",
      helperEmoji: "⚡",
    },
  },
  {
    id: 18,
    title: "Воздушный шар лопается",
    description: "Шарик летит к очень острой идее.",
    timeLimitMs: 1500,
    successText: "Шарик жив.",
    failText: "Праздник стал громче.",
    target: {
      x: 42,
      y: 43,
      width: 31,
      height: 19,
      label: "Щит",
    },
    scene: {
      type: "balloon-pin",
      emoji: "🎈",
      dangerEmoji: "📍",
      helperEmoji: "🛡️",
    },
  },
  {
    id: 19,
    title: "Ноутбук и кофе",
    description: "Кофе летит прямо в дедлайн.",
    timeLimitMs: 1450,
    successText: "Код спасён.",
    failText: "Ноутбук теперь пьёт латте.",
    target: {
      x: 31,
      y: 63,
      width: 35,
      height: 17,
      label: "Салфетка",
    },
    scene: {
      type: "coffee-laptop",
      emoji: "☕",
      dangerEmoji: "💻",
      helperEmoji: "🧻",
    },
  },
  {
    id: 20,
    title: "Черепаха на дороге",
    description: "Самый медленный экшен дня.",
    timeLimitMs: 1750,
    successText: "Движение остановлено.",
    failText: "Черепаха недовольна сервисом.",
    target: {
      x: 66,
      y: 43,
      width: 24,
      height: 19,
      label: "Стоп",
    },
    scene: {
      type: "turtle-road",
      emoji: "🐢",
      dangerEmoji: "🚙",
      helperEmoji: "🛑",
    },
  },
  {
    id: 21,
    title: "Суп убегает",
    description: "Кастрюля уже готовит побег.",
    timeLimitMs: 1450,
    successText: "Кухня спасена.",
    failText: "Суп решил путешествовать.",
    target: {
      x: 37,
      y: 68,
      width: 32,
      height: 17,
      label: "Плита",
    },
    scene: {
      type: "boiling-soup",
      emoji: "🍲",
      dangerEmoji: "♨️",
      helperEmoji: "🔘",
    },
  },
  {
    id: 22,
    title: "Подарок падает",
    description: "Конвейер потерял праздничный настрой.",
    timeLimitMs: 1550,
    successText: "Подарок пойман.",
    failText: "Сюрприз стал плоским.",
    target: {
      x: 37,
      y: 72,
      width: 34,
      height: 16,
      label: "Корзина",
    },
    scene: {
      type: "gift-conveyor",
      emoji: "🎁",
      dangerEmoji: "⬇️",
      helperEmoji: "🧺",
    },
  },
  {
    id: 23,
    title: "Снеговик тает",
    description: "Снеговик встретил слишком тёплый прогноз.",
    timeLimitMs: 1600,
    successText: "Зима продлена.",
    failText: "Снеговик стал воспоминанием.",
    target: {
      x: 28,
      y: 25,
      width: 36,
      height: 18,
      label: "Облако",
    },
    scene: {
      type: "snowman-sun",
      emoji: "⛄",
      dangerEmoji: "☀️",
      helperEmoji: "☁️",
    },
  },
  {
    id: 24,
    title: "Батарея телефона 1%",
    description: "Телефон держится на честном слове.",
    timeLimitMs: 1350,
    successText: "Телефон ожил.",
    failText: "Экран ушёл в темноту.",
    target: {
      x: 58,
      y: 63,
      width: 28,
      height: 18,
      label: "Зарядка",
    },
    scene: {
      type: "low-battery",
      emoji: "📱",
      dangerEmoji: "1%",
      helperEmoji: "🔌",
    },
  },
  {
    id: 25,
    title: "Самолётик и дерево",
    description: "Бумажная авиация входит в лес.",
    timeLimitMs: 1650,
    successText: "Полёт продолжается.",
    failText: "Посадка была резкой.",
    target: {
      x: 28,
      y: 36,
      width: 33,
      height: 18,
      label: "Ветер",
    },
    scene: {
      type: "paper-plane-tree",
      emoji: "✈️",
      dangerEmoji: "🌳",
      helperEmoji: "💨",
    },
  },
  {
    id: 26,
    title: "Мышь и сыроловка",
    description: "Мышь идёт к слишком подозрительному сыру.",
    timeLimitMs: 1500,
    successText: "Мышь выбрала безопасный сыр.",
    failText: "Мышь сделала плохой выбор.",
    target: {
      x: 25,
      y: 67,
      width: 28,
      height: 17,
      label: "Сыр рядом",
    },
    scene: {
      type: "mouse-trap",
      emoji: "🐭",
      dangerEmoji: "🪤",
      helperEmoji: "🧀",
    },
  },
  {
    id: 27,
    title: "Яйцо падает",
    description: "Яйцо выбрало драматичный спуск.",
    timeLimitMs: 1450,
    successText: "Завтрак спасён.",
    failText: "Омлет получился на полу.",
    target: {
      x: 38,
      y: 70,
      width: 34,
      height: 16,
      label: "Сковородка",
    },
    scene: {
      type: "falling-egg",
      emoji: "🥚",
      dangerEmoji: "🍳",
      helperEmoji: "🍳",
    },
  },
  {
    id: 28,
    title: "Пират и акула",
    description: "Пират падает в меню акулы.",
    timeLimitMs: 1700,
    successText: "Пират отплыл красиво.",
    failText: "Акула получила обед.",
    target: {
      x: 53,
      y: 61,
      width: 33,
      height: 18,
      label: "Лодка",
    },
    scene: {
      type: "pirate-shark",
      emoji: "🏴‍☠️",
      dangerEmoji: "🦈",
      helperEmoji: "⛵",
    },
  },
  {
    id: 29,
    title: "Космонавт улетает",
    description: "Корабль остался, космонавт пошёл гулять.",
    timeLimitMs: 1550,
    successText: "Космонавт пристёгнут.",
    failText: "Он стал спутником.",
    target: {
      x: 28,
      y: 49,
      width: 34,
      height: 16,
      label: "Трос",
    },
    scene: {
      type: "astronaut-rope",
      emoji: "🧑‍🚀",
      dangerEmoji: "🛰️",
      helperEmoji: "🪢",
    },
  },
  {
    id: 30,
    title: "Динозавр и метеорит",
    description: "История пытается нажать повтор.",
    timeLimitMs: 1500,
    successText: "Динозавр ушёл в отпуск.",
    failText: "История повторилась.",
    target: {
      x: 53,
      y: 58,
      width: 31,
      height: 20,
      label: "Портал",
    },
    scene: {
      type: "dinosaur-meteor",
      emoji: "🦖",
      dangerEmoji: "☄️",
      helperEmoji: "🌀",
    },
  },
];
